# Generated by Django 3.2.16 on 2022-11-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20221130_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='category',
        ),
    ]
