# Generated by Django 3.2.16 on 2022-11-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_remove_money_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='category',
            field=models.CharField(default='食費', max_length=10),
            preserve_default=False,
        ),
    ]
