# Generated by Django 3.2.16 on 2022-11-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_remove_money_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
