# Generated by Django 3.2.16 on 2022-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_money_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='location',
            field=models.CharField(default='明野新町', max_length=10),
            preserve_default=False,
        ),
    ]
